In [4]:
import numpy as np


In [5]:
matriz = [[1,2,3],
          [4,5,6],
          [6,7,8]]

In [6]:
a = np.array([matriz])
a.shape

(1, 3, 3)

In [7]:
a

array([[[1, 2, 3],
        [4, 5, 6],
        [6, 7, 8]]])

In [10]:
secuencia = np.arange(19)
print(secuencia)

secuencia1 = np.arange()
print(secuencia1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


TypeError: arange() requires stop to be specified.

In [ ]:
matriz[0]

In [ ]:
espacio = np.linspace(10,0,5)
print(espacio)

In [ ]:
nada = np.empty((2,3))
print(type(nada))

In [1]:
full = np.full((2,3),7)
print(full)

NameError: name 'np' is not defined

In [ ]:
azar = np.random.rand(4,3)
print(azar)

In [ ]:
# genera un objeto con nueva forma
serie = np.arange(16)
serie2 = np.reshape(serie,[8,2])
print(serie2)

In [ ]:
#rezise cambia el objeto original
serie = np.arange(16)
serie2 = np.resize(serie,[8,2])
print(serie2)

In [39]:
serie = np.arange(32).reshape([4,4,2])
serie

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])